config/routes.rb
Rails.application.routes.draw do
  get 'welcome/sugarloaf'
  get 'welcome/sugarbush'
  get 'welcome/sundayRiver'
  get 'welcome/newengland'
  get 'welcome/index'
resources :reviews do
  resources :comments, only: [:index, :new, :create]
end
resources :comments, only: [:show, :edit, :update, :destroy]
resources :welcome
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mountain.rb
class Mountain < ApplicationRecord
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :mountain
end

app/models/setup-capybara.rb
# Require the gems
require 'capybara/poltergeist'

# Configure Poltergeist to not blow up on websites with js errors aka every website with js
# See more options at https://github.com/teampoltergeist/poltergeist#customization
Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(app, js_errors: false)
end

# Configure Capybara to use Poltergeist as the driver
Capybara.default_driver = :poltergeist

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
def index
  @reviews = Review.all
end
def show
   @review = Review.find(params[:id])
end
def make_reviews
  @review = Review.find(params[:id])
  @reviews = Review.all
end
  def new
  end
  def create
   @review = Review.new(review_params)
    @review.save
    redirect_to review_path(@review)
  end
  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to review_path
  end
  private
  def review_params
params.require(:review).permit(:title,:text, :mountain_id)
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @reviews = Review.all
  end
  def sugarbush
  #  SiteVisitor.new
  #  SiteVisitor.new.visit_page('sugarbush')visit_mountain(mountain)
  visit_mountain('Sugarbush')
  @mountain = Mountain.find_by(name: 'Sugarbush')
  @review = @mountain.reviews
  end
  def sundayRiver
    visit_mountain('Sunday River')
    @mountain = Mountain.find_by(name: 'Sundayriver')
    @review = @mountain.reviews
  end
  def sugarloaf
  visit_mountain('sugarloaf')
  @mountain = Mountain.find_by(name: 'Sugarloaf')
  @review = @mountain.reviews
  end
  def show
     @review = Review.find(params[:id])
  end
    def new
    end

    def create
     @review = Review.new(review_params)
      @review.save
      redirect_to @review
    end
    private
    def review_params
      params.require(:review).permit(:title,:text)
  end
end
def visit_mountain(mountain_name)
site_visitor = SiteVisitor.new(mountain_name)
@trails = site_visitor.print_trails_open
@lifts = site_visitor.print_lifts_open
@base_depth = site_visitor.print_base_depth
@summit_depth = site_visitor.print_summit_depth
@summit_temp = site_visitor.print_summit_temp
@base_temp = site_visitor.print_base_temp
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_image(image_path,target_link,options={})
    link_to(image_tag(image_path, :border => "0"), target_link, options)
end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

end

app/views/reviews/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
  <%= link_to "Home", welcome_index_path, :class =>'dropdown-item'%>

      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Mountains
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "sugarloaf", welcome_sugarloaf_path, :class =>'dropdown-item'%>
            <%= link_to "Sugarbush", welcome_sugarbush_path, :class =>'dropdown-item'%>
                    <%= link_to "SundayRiver", welcome_sundayRiver_path, :class =>'dropdown-item'%>
          
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
<div class= "container">
<div class=”container”>
<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @review.text %>
</p>
</div>
</div>

app/views/welcome/berkshireEast.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
  <%= link_to "Home", welcome_index_path, :class =>'dropdown-item'%>

      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "sugarloaf", welcome_sugarloaf_path, :class =>'dropdown-item'%>

            <%= link_to "Sugarbush", welcome_sugarbush_path, :class =>'dropdown-item'%>

              <%= link_to "Sunapee", welcome_mountSunapee_path, :class =>'dropdown-item'%>
                <%= link_to "Mt.Abram", welcome_mountAbram_path, :class =>'dropdown-item'%>
                  <%= link_to "Wachusett", welcome_wachusettMountain_path, :class =>'dropdown-item'%>
                    <%= link_to "SundayRiver", welcome_sundayRiver_path, :class =>'dropdown-item'%>
                      <%= link_to "PatsPeak", welcome_patsPeak_path, :class =>'dropdown-item'%>

          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<h1>Welcome#berkshireEast</h1>
<p>Find me in app/views/welcome/berkshireEast.html.erb</p>
<h3> Trails open </h3>
<%= @trails %>
<h3> Lifts open </h3>
<%= @lifts %>
<h3> Base snow depth </h3>
<%= @base_depth %>
<h3> Summit depth </h3>
<%= @summit_depth %>
<h3> base temperature </h3>
<%= @base_temp %>
<h3> Summit temperature </h3>
<%= @summit_temp %>

<h2> User Reviews</h2>
<%= form_with scope: :review, url: reviews_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.hidden_field :mountain_id, value: @mountain.id %>
    <%= form.submit %>
  </p>
<% end %>


<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @review.each do |review| %>
    <tr>
      <td><%= review.title %></td>
      <td><%= review.text %></td>
      <td><%= link_to 'Show', review_path(review) %></td>
    </tr>
  <% end %>
</table>

app/views/welcome/blueHillsSkiArea.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
  <%= link_to "Home", welcome_index_path, :class =>'dropdown-item'%>

      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "sugarloaf", welcome_sugarloaf_path, :class =>'dropdown-item'%>

            <%= link_to "Sugarbush", welcome_sugarbush_path, :class =>'dropdown-item'%>

              <%= link_to "Sunapee", welcome_mountSunapee_path, :class =>'dropdown-item'%>
                <%= link_to "Mt.Abram", welcome_mountAbram_path, :class =>'dropdown-item'%>
                  <%= link_to "Wachusett", welcome_wachusettMountain_path, :class =>'dropdown-item'%>
                    <%= link_to "SundayRiver", welcome_sundayRiver_path, :class =>'dropdown-item'%>
                      <%= link_to "PatsPeak", welcome_patsPeak_path, :class =>'dropdown-item'%>

          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<h1>Welcome#blueHillsSkiArea</h1>
<p>Find me in app/views/welcome/blueHillsSkiArea.html.erb</p>
<h3> Trails open </h3>
<%= @trails %>
<h3> Lifts open </h3>
<%= @lifts %>
<h3> Base snow depth </h3>
<%= @base_depth %>
<h3> Summit depth </h3>
<%= @summit_depth %>
<h3> base temperature </h3>
<%= @base_temp %>
<h3> Summit temperature </h3>
<%= @summit_temp %>

<h2> User Reviews</h2>
<%= form_with scope: :review, url: reviews_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.hidden_field :mountain_id, value: @mountain.id %>
    <%= form.submit %>
  </p>
<% end %>


<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @review.each do |review| %>
    <tr>
      <td><%= review.title %></td>
      <td><%= review.text %></td>
      <td><%= link_to 'Show', review_path(review) %></td>
    </tr>
  <% end %>
</table>

app/views/welcome/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">

      </li>
      <li class="nav-item">
      <%= link_to "Home", welcome_index_path, :class =>'nav-link'%>


      </li>
  
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Mountains
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "sugarloaf", welcome_sugarloaf_path, :class =>'dropdown-item'%>
            <%= link_to "Sugarbush", welcome_sugarbush_path, :class =>'dropdown-item'%>
                    <%= link_to "SundayRiver", welcome_sundayRiver_path, :class =>'dropdown-item'%>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Steamboat Springs</a>
        </div></li></ul></div></nav>
<div class="container">
<h1>Welcome to New England</h1>
<p>Join us in Skiing the East!</p>
</div>
<div class="container">
  <div class="d-flex flex-column">

<%= link_to image_tag('sugarbush-bannerDONEDONE.jpg'), welcome_sugarbush_path%>
<%= link_to image_tag('sundayriverbanner.jpg'), welcome_sundayRiver_path%>
<%= link_to image_tag('sugarloafbannerDONE.jpg'), welcome_sugarloaf_path%>


    <div class="w-100"></div>

  </div>
</div>

<br />

app/views/welcome/mountAbram.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
  <%= link_to "Home", welcome_index_path, :class =>'dropdown-item'%>

      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "sugarloaf", welcome_sugarloaf_path, :class =>'dropdown-item'%>

            <%= link_to "Sugarbush", welcome_sugarbush_path, :class =>'dropdown-item'%>

              <%= link_to "Sunapee", welcome_mountSunapee_path, :class =>'dropdown-item'%>
                <%= link_to "Mt.Abram", welcome_mountAbram_path, :class =>'dropdown-item'%>
                  <%= link_to "Wachusett", welcome_wachusettMountain_path, :class =>'dropdown-item'%>
                    <%= link_to "SundayRiver", welcome_sundayRiver_path, :class =>'dropdown-item'%>
                      <%= link_to "PatsPeak", welcome_patsPeak_path, :class =>'dropdown-item'%>

          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<h1>Welcome#mountAbram</h1>
<p>Find me in app/views/welcome/mountAbram.html.erb</p>
<h3> Trails open </h3>
<%= @trails %>
<h3> Lifts open </h3>
<%= @lifts %>
<h3> Base snow depth </h3>
<%= @base_depth %>
<h3> Summit depth </h3>
<%= @summit_depth %>
<h3> base temperature </h3>
<%= @base_temp %>
<h3> Summit temperature </h3>
<%= @summit_temp %>

<h2> User Reviews</h2>
<%= form_with scope: :review, url: reviews_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.hidden_field :mountain_id, value: @mountain.id %>
    <%= form.submit %>
  </p>
<% end %>


<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @review.each do |review| %>
    <tr>
      <td><%= review.title %></td>
      <td><%= review.text %></td>
      <td><%= link_to 'Show', review_path(review) %></td>
    </tr>
  <% end %>
</table>

app/views/welcome/mountSunapee.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
  <%= link_to "Home", welcome_index_path, :class =>'dropdown-item'%>

      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "sugarloaf", welcome_sugarloaf_path, :class =>'dropdown-item'%>

            <%= link_to "Sugarbush", welcome_sugarbush_path, :class =>'dropdown-item'%>

              <%= link_to "Sunapee", welcome_mountSunapee_path, :class =>'dropdown-item'%>
                <%= link_to "Mt.Abram", welcome_mountAbram_path, :class =>'dropdown-item'%>
                  <%= link_to "Wachusett", welcome_wachusettMountain_path, :class =>'dropdown-item'%>
                    <%= link_to "SundayRiver", welcome_sundayRiver_path, :class =>'dropdown-item'%>
                      <%= link_to "PatsPeak", welcome_patsPeak_path, :class =>'dropdown-item'%>

          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<h1>Welcome#mountSunapee</h1>
<p>Find me in app/views/welcome/mountSunapee.html.erb</p>
<h3> Trails open </h3>
<%= @trails %>
<h3> Lifts open </h3>
<%= @lifts %>
<h3> Base snow depth </h3>
<%= @base_depth %>
<h3> Summit depth </h3>
<%= @summit_depth %>
<h3> base temperature </h3>
<%= @base_temp %>
<h3> Summit temperature </h3>
<%= @summit_temp %>

<h2> User Reviews</h2>
<%= form_with scope: :review, url: reviews_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.hidden_field :mountain_id, value: @mountain.id %>
    <%= form.submit %>
  </p>
<% end %>


<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @review.each do |review| %>
    <tr>
      <td><%= review.title %></td>
      <td><%= review.text %></td>
      <td><%= link_to 'Show', review_path(review) %></td>
    </tr>
  <% end %>
</table>

app/views/welcome/patsPeak.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
  <%= link_to "Home", welcome_index_path, :class =>'dropdown-item'%>

      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "sugarloaf", welcome_sugarloaf_path, :class =>'dropdown-item'%>

            <%= link_to "Sugarbush", welcome_sugarbush_path, :class =>'dropdown-item'%>

              <%= link_to "Sunapee", welcome_mountSunapee_path, :class =>'dropdown-item'%>
                <%= link_to "Mt.Abram", welcome_mountAbram_path, :class =>'dropdown-item'%>
                  <%= link_to "Wachusett", welcome_wachusettMountain_path, :class =>'dropdown-item'%>
                    <%= link_to "SundayRiver", welcome_sundayRiver_path, :class =>'dropdown-item'%>
                      <%= link_to "PatsPeak", welcome_patsPeak_path, :class =>'dropdown-item'%>

          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<h1>Welcome#patsPeak</h1>
<p>Find me in app/views/welcome/patsPeak.html.erb</p>
<h3> Trails open </h3>
<%= @trails %>
<h3> Lifts open </h3>
<%= @lifts %>
<h3> Base snow depth </h3>
<%= @base_depth %>
<h3> Summit depth </h3>
<%= @summit_depth %>
<h3> base temperature </h3>
<%= @base_temp %>
<h3> Summit temperature </h3>
<%= @summit_temp %>

<h2> User Reviews</h2>
<%= form_with scope: :review, url: reviews_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.hidden_field :mountain_id, value: @mountain.id %>
    <%= form.submit %>
  </p>
<% end %>


<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @review.each do |review| %>
    <tr>
      <td><%= review.title %></td>
      <td><%= review.text %></td>
      <td><%= link_to 'Show', review_path(review) %></td>
    </tr>
  <% end %>
</table>

app/views/welcome/wachusettMountain.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
  <%= link_to "Home", welcome_index_path, :class =>'dropdown-item'%>

      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "sugarloaf", welcome_sugarloaf_path, :class =>'dropdown-item'%>

            <%= link_to "Sugarbush", welcome_sugarbush_path, :class =>'dropdown-item'%>

              <%= link_to "Sunapee", welcome_mountSunapee_path, :class =>'dropdown-item'%>
                <%= link_to "Mt.Abram", welcome_mountAbram_path, :class =>'dropdown-item'%>
                  <%= link_to "Wachusett", welcome_wachusettMountain_path, :class =>'dropdown-item'%>
                    <%= link_to "SundayRiver", welcome_sundayRiver_path, :class =>'dropdown-item'%>
                      <%= link_to "PatsPeak", welcome_patsPeak_path, :class =>'dropdown-item'%>

          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<h1>wachusett Mountain</h1>

<h3> Trails open </h3>
<%= @trails %>
<h3> Lifts open </h3>
<%= @lifts %>
<h3> Base snow depth </h3>
<%= @base_depth %>
<h3> Summit depth </h3>
<%= @summit_depth %>
<h3> base temperature </h3>
<%= @base_temp %>
<h3> Summit temperature </h3>
<%= @summit_temp %>


<%= form_with scope: :review, url: reviews_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.hidden_field :mountain_id, value: @mountain.id %>
    <%= form.submit %>
  </p>
<% end %>
<h2> User Reviews</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @review.each do |review| %>
    <tr>
      <td><%= review.title %></td>
      <td><%= review.text %></td>
      <td><%= link_to 'Show', review_path(review) %></td>
    </tr>
  <% end %>
</table>